### ISSUE TITLE
HA will be dropping support for bluepy; Bleak will be the recommended library

### ISSUE THREAD

**Issue by strikeir13** [custom-components/sensor.airthings_wave#84] opened 2022-06-21 11:38 UTC
Just saw on Twitter from one of the HA devs that they will stop supporting bluepy at some point (likely soon): 

https://twitter.com/pvizeli/status/1539151074745106433

"@pvizeli: We can't longer support the unmaintained old library blueby at @home_assistant. This means your custom/integration which uses this, stops working. We strongly recommend replacing it with Bleak, a maintained and modern BLE python library"

Not sure what that means for this component, but I wanted to bring it up since I've been using it without issues for over a year.

**Comment by lone-cloud** [comment] 2022-07-06 22:12
This ended up breaking this integration as per #86

**Comment by MartyTremblay** [comment] 2022-07-11 14:35
Closing and marking as dupe of #86. Thanks for for being proactive @strikeir13

**Closed by MartyTremblay** 2022-07-11 14:35 UTC
